title = "home"
languageCode = "en-us"

# Theme to use
theme = "simple"

# Pagination
paginate = 100
paginatePath = "page"

# Google analytics
googleAnalytics = "UA-144580607-2"

# Copyright
copyright = "© 2019 — the wash maintainers"

# Highlighting
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "vs"

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Menu
[menu]
  # Header
  [[menu.main]]
    url = "docs"
    name = "docs"
    weight = 1
  [[menu.main]]
    url = "#"
    name = "news"
    weight = 4
  [[menu.main]]
    url = "https://github.com/puppetlabs/wash"
    name = "github"
    weight = 7
  [[menu.main]]
    url = "https://github.com/puppetlabs/wash/releases"
    name = "download"
    weight = 10
  [[menu.main]]
    url = "https://puppetcommunity.slack.com/app_redirect?channel=wash"
    name = "slack"
    weight = 13

# Links format
[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  # Date format (default: Jan 2, 2006)
  # datefmt  = "Jan 2, 2006"
