title: Wash
description: "Wide Area SHell: a cloud-native shell for bringing remote infrastructure to your terminal."
url: https://puppetlabs.github.io
base_url: /wash
title_image: /assets/images/wash-logo.png
google_analytics: UA-144580607-2
exclude: [vendor, Boltdir, acceptance, modules, .git, Gemfile, Gemfile.lock]

collections:
  tutorials:
    output: true

defaults:
  - scope:
      type: tutorials
    values:
      layout: tutorial
  - scope:
      type: posts
    values:
      layout: post
      permalink: /:categories/:year-:month-:day-:title

plugins:
  - jekyll-feed
