name: Update website on push

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Prepare destination
      run: |
        set -e
        git remote set-url origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git worktree add -B gh-pages website/public origin/gh-pages
        cd website/public
        git rm -r '*'
        touch .nojekyll
      env:
        GITHUB_TOKEN: ${{ secrets.HOMEBREW_DEPLOY_TOKEN }}
    - name: Checkout latest tag
      run: git checkout $(git describe --tags $(git rev-list --tags --max-count=1))
    - name: Build release website
      uses: docker://peaceiris/hugo:v0.57.1
      with:
        args: -s website -d public --gc -b https://puppetlabs.github.io/wash --minify
    - name: Checkout master
      run: git checkout $GITHUB_SHA
    - name: Add dev website
      uses: docker://peaceiris/hugo:v0.57.1
      with:
        args: -s website -d public/dev --gc -b https://puppetlabs.github.io/wash/dev --minify
    - name: Deploy
      run: |
        set -e
        cd website/public
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add --all
        if [ -n "$(git status --porcelain)" ]; then
          git commit -s -m "Publish $(git describe --tags $(git rev-list --tags --max-count=1)) + ${GITHUB_SHA}"
          git push origin gh-pages
        fi
